phases:
- phase: GettingStarted
  queue: Hosted VS2017
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build GettingStarted
    inputs:
      projects: '.\getting-started\GettingStarted.sln'
- phase: GitHubLabeler
  queue: Hosted VS2017
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build GettingStarted
    inputs:
      projects: '.\github-labeler\GitHubLabeler.sln'