
jobs:
  # - job:
  #   pool: 
  #     vmImage: 'windows-2022'
  #   steps:
  #     - task: DotNetCoreCLI@2
  #       inputs:
  #         command: 'build'
  #         projects: '.\samples\csharp\getting-started\DeepLearning_ObjectDetection_Onnx\ObjectDetection.sln'

- job: CreditCardFraudDetection
  pool: 
    vmImage: 'windows-2022'
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build CreditCardFraudDetection (BinaryClassification)
    inputs:
      command: 'build'
      projects: '.\samples\csharp\getting-started\BinaryClassification_CreditCardFraudDetection\CreditCardFraudDetection.sln'

- job: CreditCardFraudDetection2
  pool:
    vmImage: 'windows-2022'  
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build CreditCardFraudDetection (AnomalyDetection)
    inputs:
      command: 'build'    
      projects: '.\samples\csharp\getting-started\AnomalyDetection_CreditCardFraudDetection\CreditCardFraudDetection.sln'

- job: SentimentAnalysis
  pool:
    vmImage: 'windows-2022'  
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build SentimentAnalysis (BinaryClassification)
    inputs:
      command: 'build'    
      projects: '.\samples\csharp\getting-started\BinaryClassification_SentimentAnalysis\SentimentAnalysis-Solution.sln'

- job: HeartDiseaseDetection
  pool:
    vmImage: 'windows-2022'  
  steps:
  - task: DotNetCoreCLI@2
    displayName: Heart Disease Detection (BinaryClassification)
    inputs:
      command: 'build'    
      projects: '.\samples\csharp\getting-started\BinaryClassification_HeartDiseaseDetection\HeartDiseaseDetection.sln'

- job: SpamDetection
  pool:
    vmImage: 'windows-2022'  
  steps:
  - task: DotNetCoreCLI@2
    displayName: Spam Detection (BinaryClassification)
    inputs:
      command: 'build'    
      projects: '.\samples\csharp\getting-started\BinaryClassification_SpamDetection\SpamDetectionConsoleApp.sln'

- job: CustomerSegmentation
  pool:
    vmImage: 'windows-2022'  
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build CustomerSegmentation (Clustering)
    inputs:
      command: 'build'    
      projects: '.\samples\csharp\getting-started\Clustering_CustomerSegmentation\CustomerSegmentation.sln'

- job: IrisClustering
  pool:
    vmImage: 'windows-2022'  
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build Iris (Clustering)
    inputs:
      command: 'build'    
      projects: '.\samples\csharp\getting-started\Clustering_Iris\Clustering_Iris.sln'

- job: TensorFlowScorer
  pool:
    vmImage: 'windows-2022'  
  steps:
  - task: DotNetCoreCLI@2
    displayName: TensorFlow Scorer (Image Classification)
    inputs:
      command: 'build'    
      projects: '.\samples\csharp\getting-started\DeepLearning_ImageClassification_TensorFlow\TFModelScorer.sln'

- job: TensorFlowFeaturizerEstimator
  pool:
    vmImage: 'windows-2022'  
  steps:
  - task: DotNetCoreCLI@2
    displayName: TensorFlow Featurizer Estimator (Image Classification)
    inputs:
      command: 'build'    
      projects: '.\samples\csharp\getting-started\DeepLearning_TensorFlowEstimator\TFFeaturizerEstimator.sln'

- job: IrisMultiClass
  pool:
    vmImage: 'windows-2022'  
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build Iris (MulticlassClassification)
    inputs:
      command: 'build'    
      projects: '.\samples\csharp\getting-started\MulticlassClassification_Iris\MulticlassClassification_Iris.sln'

- job: BikeSharingDemand
  pool:
    vmImage: 'windows-2022'  
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build BikeSharingDemand (Regression)
    inputs:
      command: 'build'    
      projects: '.\samples\csharp\getting-started\Regression_BikeSharingDemand\BikeSharingDemand.sln'

- job: TaxiFarePrediction
  pool:
    vmImage: 'windows-2022'  
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build TaxiFarePrediction (Regression)
    inputs:
      command: 'build'    
      projects: '.\samples\csharp\getting-started\Regression_TaxiFarePrediction\TaxiFarePrediction.sln'

- job: GitHubLabeler
  pool:
    vmImage: 'windows-2022'  
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build GitHubLabeler
    inputs:
      command: 'build'    
      projects: '.\samples\csharp\end-to-end-apps\MulticlassClassification-GitHubLabeler\GitHubLabeler.sln'

- job: eShopDashboardML
  pool:
    vmImage: 'windows-2022'  
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build eShopDashboardML (Regression)
    inputs:
      command: 'build'    
      projects: '.\samples\csharp\end-to-end-apps\Forecasting-Sales\eShopDashboardML.sln'

- job: MovieRecommenderE2E
  pool:
    vmImage: 'windows-2022'  
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build MovieRecommender E2E (Recommendation)
    inputs:
      command: 'build'    
      projects: '.\samples\csharp\end-to-end-apps\Recommendation-MovieRecommender\Recommendation_MovieRecommenderApp.sln'

- job: MovieRecommenderMF
  pool:
    vmImage: 'windows-2022'  
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build MovieRecommender MF (Recommendation)
    inputs:
      command: 'build'    
      projects: '.\samples\csharp\getting-started\MatrixFactorization_MovieRecommendation\MovieRecommendation.sln'

- job: Mnist
  pool:
    vmImage: 'windows-2022'  
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build Mnist (MulticlassClassification)
    inputs:
      command: 'build'    
      projects: '.\samples\csharp\getting-started\MulticlassClassification_MNIST\MNISTConsoleApp.sln'

- job: SalesSpikeAndChangeDetection
  pool:
    vmImage: 'windows-2022'  
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build Sales spike and change Detection (Anomaly Detection)
    inputs:
      command: 'build'    
      projects: '.\samples\csharp\getting-started\AnomalyDetection_Sales\SpikeDetection.sln'

- job: PowerConsumptionAnomalyDetection
  pool:
    vmImage: 'windows-2022'  
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build Power Anomaly Detection (Time Series)
    inputs:
      command: 'build'    
      projects: '.\samples\csharp\getting-started\AnomalyDetection_PowerMeterReadings\PowerAnomalyDetection.sln'

- job: ObjectDetectionConsoleApp
  pool:
    vmImage: 'windows-2022'  
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build Object Detection (Onnx Scorer)
    inputs:
      command: 'build'    
      projects: '.\samples\csharp\getting-started\DeepLearning_ObjectDetection_Onnx\ObjectDetection.sln'

- job: ObjectDetectionE2EAPP
  pool:
    vmImage: 'windows-2022'  
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core 3.1'
    inputs:
      version: 3.1.x
      includePreviewVersions: true
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - task: DotNetCoreCLI@2
    displayName: Build Object Detection E2E (Onnx Scorer)
    inputs:
      command: 'build'    
      projects: '.\samples\csharp\end-to-end-apps\ObjectDetection-Onnx\OnnxObjectDetection.sln'

- job: SalesSpikeChangeDetectionE2E
  pool:
    vmImage: 'windows-2022'  
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build Sales spike and change Detection E2E(Anomaly Detection)
    inputs:
      command: 'build'    
      projects: '.\samples\csharp\end-to-end-apps\AnomalyDetection-Sales\SpikeDetectionTemporaryApp.sln'

- job: ScalableMLModelOnWebAPIIntegrationPkg
  pool:
    vmImage: 'windows-2022'  
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build Scalable ML Model On WebAPI Integration Pkg
    inputs:
      command: 'build'    
      projects: '.\samples\csharp\end-to-end-apps\ScalableMLModelOnWebAPI-IntegrationPkg\ScalableMLModelOnWebAPI-IntegrationPkg.sln'

- job: DatabaseIntegration
  pool:
    vmImage: 'windows-2022'  
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core 3.1'
    inputs:
      version: 3.1.x
      includePreviewVersions: true
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - task: DotNetCoreCLI@2
    displayName: Build Database Integration
    inputs:
      command: 'build'    
      projects: '.\samples\csharp\getting-started\DatabaseIntegration\DatabaseIntegration.sln'

