phases:
- phase: CSharpGettingStarted
  queue: Hosted VS2017
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build C# GettingStarted
    inputs:
      projects: '.\samples\csharp\getting-started\GettingStarted.sln'

- phase: FSharpGettingStarted
  queue: Hosted VS2017
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build F# GettingStarted
    inputs:
      projects: '.\samples\fsharp\getting-started\GettingStarted.sln'

- phase: BinaryClasification_Titanic
  queue: Hosted VS2017
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build BinaryClasification_Titanic
    inputs:
      projects: '.\samples\examples\BinaryClasification_Titanic\BinaryClasification_Titanic.sln'

- phase: GitHubLabeler
  queue: Hosted VS2017
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build GitHubLabeler
    inputs:
      projects: '.\samples\end-to-end-apps\github-labeler\GitHubLabeler.sln'