
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace MovieRecommender_Console
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            MovieRecommender.ModelInput sampleData = new MovieRecommender.ModelInput()
            {
                UserId = 1F,
                MovieId = 1F,
                Timestamp = 9.649827E+08F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = MovieRecommender.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Rating with predicted Rating from sample data...\n\n");


            Console.WriteLine($"UserId: {1F}");
            Console.WriteLine($"MovieId: {1F}");
            Console.WriteLine($"Rating: {4F}");
            Console.WriteLine($"Timestamp: {9.649827E+08F}");


            Console.WriteLine($"\n\nPredicted Rating: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
