// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using Microsoft.ML;
using StopSignDetectionML.Model;
using System.Net.Http;
using Microsoft.ML.Trainers;
using System.Web;
using System.Net;

namespace StopSignDetectionML.Model
{
    public class ConsumeModel
    {
        private static Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictionEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(CreatePredictionEngine);

        private static WebClient client = new WebClient();

        public static string MLNetModelPath = "MLModel.zip";

        // For more info on consuming ML.NET models, visit https://aka.ms/mlnet-consume
        // Method for consuming model in your app
        public static ModelOutput Predict(ModelInput input)
        {
            ModelOutput result = PredictionEngine.Value.Predict(input);
            return result;
        }

        public static PredictionEngine<ModelInput, ModelOutput> CreatePredictionEngine()
        {
            // Create new MLContext
            MLContext mlContext = new MLContext();

            // Load model & create prediction engine
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var modelInputSchema);

            var predEngine = mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);

             return predEngine;
        }

        private static void DownloadModel()
        {
            //WebClient client = new WebClient();
            string fileName = MLNetModelPath;
            string url = $"https://aka.ms/mlnet-object-detection-tutorial-model";

            client.DownloadFile(url, fileName);

            //Console.WriteLine("Downloaded model to: " + MLNetModelPath);
        }
    }
}
