// This file was auto-generated by ML.NET Model Builder. 

using System;
using StopSignDetectionML.Model;

namespace StopSignDetectionML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                ImageSource = @"test-image1.jpeg",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine($"ImageSource: {sampleData.ImageSource}");
            Console.WriteLine("\n\nPredicted Boxes:\n");
            Console.WriteLine(predictionResult);
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
