// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace SentimentRazor
{
    public partial class SentimentAnalysis
    {
        /// <summary>
        /// model input class for SentimentAnalysis.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"Sentiment")]
            public float Sentiment { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"SentimentText")]
            public string SentimentText { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"LoggedIn")]
            public bool LoggedIn { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for SentimentAnalysis.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Sentiment")]
            public uint Sentiment { get; set; }

            [ColumnName(@"SentimentText")]
            public string SentimentText { get; set; }

            [ColumnName(@"LoggedIn")]
            public bool LoggedIn { get; set; }

            [ColumnName(@"PredictedLabel")]
            public float PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("SentimentAnalysis.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
