// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace RestaurantViolationsML.Model
{
    public class ModelInput
    {
        [ColumnName("inspection_type"), LoadColumn(0)]
        public string Inspection_type { get; set; }


        [ColumnName("violation_description"), LoadColumn(1)]
        public string Violation_description { get; set; }


        [ColumnName("risk_category"), LoadColumn(2)]
        public string Risk_category { get; set; }


    }
}
