// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace RestaurantViolationsML.Model
{
    public class ModelInput
    {
        [ColumnName("business_id"), LoadColumn(0)]
        public float Business_id { get; set; }


        [ColumnName("business_name"), LoadColumn(1)]
        public string Business_name { get; set; }


        [ColumnName("business_address"), LoadColumn(2)]
        public string Business_address { get; set; }


        [ColumnName("business_city"), LoadColumn(3)]
        public string Business_city { get; set; }


        [ColumnName("business_state"), LoadColumn(4)]
        public string Business_state { get; set; }


        [ColumnName("business_postal_code"), LoadColumn(5)]
        public string Business_postal_code { get; set; }


        [ColumnName("business_latitude"), LoadColumn(6)]
        public float Business_latitude { get; set; }


        [ColumnName("business_longitude"), LoadColumn(7)]
        public float Business_longitude { get; set; }


        [ColumnName("business_location"), LoadColumn(8)]
        public string Business_location { get; set; }


        [ColumnName("business_phone_number"), LoadColumn(9)]
        public float Business_phone_number { get; set; }


        [ColumnName("inspection_id"), LoadColumn(10)]
        public string Inspection_id { get; set; }


        [ColumnName("inspection_date"), LoadColumn(11)]
        public string Inspection_date { get; set; }


        [ColumnName("inspection_score"), LoadColumn(12)]
        public float Inspection_score { get; set; }


        [ColumnName("inspection_type"), LoadColumn(13)]
        public string Inspection_type { get; set; }


        [ColumnName("violation_id"), LoadColumn(14)]
        public string Violation_id { get; set; }


        [ColumnName("violation_description"), LoadColumn(15)]
        public string Violation_description { get; set; }


        [ColumnName("risk_category"), LoadColumn(16)]
        public string Risk_category { get; set; }


    }
}
